version: "3.9"

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./kg:/fuseki
    environment:
      - ADMIN_PASSWORD=admin
    command: >
      --mem /emotion

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: emotion-api
    ports:
      - "8000:8000"
    depends_on:
      - fuseki
